name: Deploy doc to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2.3.1

    - name: Setup Cargo ğŸšš
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        export PATH="$HOME/.cargo/bin:$PATH"
        rustup toolchain install nightly
        rustup default nightly
        rustup target add wasm32-wasi

    - name: Build ğŸ”§
      run: |
        RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly rustdoc -p wasmedge_wasi_socket --target wasm32-wasi --lib

    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: target/wasm32-wasi/doc
